import DetailPage from "@/components/DetailPage";
import Head from "next/head";

function index({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DetailPage data={data} />
      </main>
    </>
  );
}
export const getServerSideProps = async (context) => {
  const { id } = context.params;
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_API_PROTOCOL}://${process.env.NEXT_PUBLIC_API_HOST}/wp-json/stafford/v1/project/${id}`
  );

  const data = await response.json();
  return {
    props: {
      data: data?.response || null,
    },
  };
};
export default index;
